site_name: earthcarekit 0.12.0 documentation

repo_url: https://github.com/TROPOS-RSD/earthcarekit

extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.image.lightbox
  language: en
  logo: https://raw.githubusercontent.com/TROPOS-RSD/earthcarekit-docs-assets/refs/heads/main/assets/images/logos/earthcarekit-icon-white.png
  favicon: https://raw.githubusercontent.com/TROPOS-RSD/earthcarekit-docs-assets/refs/heads/main/assets/images/logos/earthcarekit-favicon-blue.png
  palette:
    # Auto/light/dark mode toggle
    # Automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/circle-half-stroke
        name: Light color mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: fontawesome/solid/sun
        name: Dark color mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: fontawesome/solid/moon
        name: System color mode

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: vs
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - tables

plugins:
  - autorefs
  - search
  - macros
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
  - glightbox:
      skip_classes:
        - skip-lightbox

nav:
  - Getting started:
    - About: index.md
    - Setup: setup.md
    - Colormaps: colormaps.md
    - Supported products: supported_products.md
  - Tutorials:
    - Quickstart: tutorials/quickstart.md
    - Working with profiles: tutorials/profiles.md
    - Rebin X-MET along-track: tutorials/xmet_rebin_along_track.md
    - Curtain plot customizations: tutorials/curtain_plot_customization.md
    - Map plots: tutorials/maps.md
  - Command-line interface tools:
    - Download tool: cli/ecdownload.md
    - Quicklook tool: cli/ecquicklook.md
  - API reference:
    - earthcarekit: api_ref.md
    - earthcarekit.geo: api_ref/geo.md
    - earthcarekit.read: api_ref/read.md
    - earthcarekit.stats: api_ref/stats.md
  
copyright: |
  <span style="opacity: 0.7;">Copyright &copy; 2025 TROPOS</span>
  </br>
  <span style="opacity: 0.7;">Developed at</span> <a href="https://www.tropos.de/en/">Leibniz Institute for Tropospheric Research</a>
  </br>
  <span style="opacity: 0.7;">Documentation made with</span> <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>

extra:
  version: "0.12.0"
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TROPOS-RSD/earthcarekit
      name: GitHub
    - icon: simple/zenodo
      link: https://doi.org/10.5281/zenodo.16813294
      name: Zenodo